"""empty message

Revision ID: c12823191070
Revises: 1af05b696358
Create Date: 2024-01-25 23:23:30.955561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c12823191070'
down_revision = '1af05b696358'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.alter_column('location',
               existing_type=sa.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.drop_column('email')
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('property', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=255), nullable=False))
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=255), nullable=False))
        batch_op.alter_column('location',
               existing_type=sa.String(length=255),
               type_=sa.FLOAT(),
               existing_nullable=False)

    # ### end Alembic commands ###
